markdown: kramdown

remote_theme: zendesk/jekyll-theme-zendesk-garden@main

sidebar:
  - [Untuk Pengguna](https://annisaraihana.github.io/Server-Monitoring/#untuk-pengguna)
  - [Untuk Pengembang](https://annisaraihana.github.io/Server-Monitoring/#untuk-pengembang)
